name: Workflow using YAML from Test2

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  call-docker-workflow:
    uses: MyOrgHacker/Test2/.github/workflows/docker-image.yml@main
    secrets: inherit

  call-trivy-workflow:
    uses: MyOrgHacker/Test2/.github/workflows/trivy.yml@main
    secrets: inherit

  call-shiftleft-workflow:
    uses: MyOrgHacker/Test2/.github/workflows/shiftleft-analysis.yml@main
    secrets: inherit

  call-codeql-workflow:
    uses: MyOrgHacker/Test2/.github/workflows/codeql.yml@main
    secrets: inherit
